version: '3.8'

services:
  bot:
    image: ghcr.io/yukesh0a/clevr-bot:latest
    container_name: clevr-bot
    restart: always
    env_file:
      - .env
    depends_on:
      clevr-db:
        condition: service_healthy

  clevr-db:
    image: postgres:16-alpine
    container_name: clevr-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-clevr_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-super_secret_password}
      POSTGRES_DB: ${DB_NAME:-clevr_bot_db}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: